FROM python:3.10.12

WORKDIR /app/dashboard

COPY ./dashboard .

ENV DASHBOARD_PORT=8501
ENV TZ=UTC

RUN pip install --no-cache-dir -r requirements.txt

CMD ["sh", "-c", "streamlit run --server.port=$DASHBOARD_PORT 01_📖_Dashboard.py"]
