# Build stage
FROM golang:1.23.4 AS build

WORKDIR /app/api

# CGO (C bindings for Go)
# When CGO_ENABLED=0, Go builds a fully statically linked binary, meaning it does not rely on any external C libraries.
# This ensures that the binary is self-contained and portable.
ARG CGO_ENABLED=0

COPY ./api .

COPY ./defaults ../defaults

RUN go mod download

RUN go build -o main .

# Run stage
FROM alpine:latest

WORKDIR /app/api

ENV GIN_MODE=release
ENV API_PORT=8080
ENV TZ=UTC

HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
  CMD curl -f http://localhost:8080/v1/health | grep OK || exit
 
# Copy the compiled binary from the build stage
COPY --from=build /app/api/main .
COPY --from=build /app/defaults ../defaults

CMD ["./main"]
