FROM golang:1.24.0 AS builder

WORKDIR /app/api

COPY ./api .

RUN go mod download

RUN CGO_ENABLED=0 go build -o main .

FROM debian:bookworm-slim AS runtime

RUN apt update && apt install -y --no-install-recommends \
  chromium \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libatspi2.0-0 \
  libx11-6 \
  libxcomposite1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libxcb1 \
  libxkbcommon0 \
  libpango-1.0-0 \
  libcairo2 \
  libasound2 \
  libglib2.0-0 \
  libnss3 \
  libdbus-1-dev \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app/api

COPY --from=builder /app/api/main .
COPY ./defaults/default_cover_img.jpg ../defaults/default_cover_img.jpg

ENV ROD_BROWSER_PATH=/usr/bin/chromium
ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium
ENV GIN_MODE=release
ENV API_PORT=8080
ENV TZ=UTC

CMD ["./main"]
